micronaut:
  application:
    name: micronautJpaDemo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/mytestdb
    username: mytestdb
    password: mytestdb
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
